# Generated by Django 4.0.8 on 2022-11-29 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='address.country')),
            ],
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='address.province')),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('street_address', models.CharField(max_length=555)),
                ('country', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='address.country')),
                ('district', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='address.district')),
                ('province', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='address.province')),
            ],
        ),
    ]
