# Generated by Django 4.0.8 on 2022-12-11 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0002_alter_address_country_alter_address_district_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='district',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='province',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
