# Generated by Django 4.0.8 on 2022-11-29 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('address', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=555)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=555)),
                ('rating', models.DecimalField(decimal_places=1, max_digits=2)),
                ('price_level', models.IntegerField(null=True)),
                ('description', models.TextField()),
                ('address', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='address.address')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locations.category')),
            ],
        ),
    ]
