# Generated by Django 4.0.8 on 2022-12-14 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_alter_location_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='rating',
        ),
    ]
