# Generated by Django 4.0.8 on 2022-12-14 15:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0010_alter_imagestorage_id_alter_review_review_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagestorage',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='review',
            name='review_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 14, 22, 16, 12, 815117)),
        ),
    ]
